// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiV1WmsDispatchTasksByTaskIdData, DeleteApiV1WmsDispatchTasksByTaskIdResponses, GetApiWmsLocationsTestDbData, GetApiWmsLocationsTestDbResponses, GetApiWmsLocationsTestExceptionData, GetApiWmsLocationsTestExceptionResponses, GetApiWmsLocationsTestTelemetryData, GetApiWmsLocationsTestTelemetryResponses, PostApiSysAuthLoginData, PostApiSysAuthLoginResponses, PostApiV1WmsDispatchTasksData, PostApiV1WmsDispatchTasksResponses, PostApiV1XinsongReportRobotStatusData, PostApiV1XinsongReportRobotStatusResponses, PostApiWmsLocationsByLocationCodeLockData, PostApiWmsLocationsByLocationCodeLockResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 派发 AGV 搬运任务
 */
export const postApiV1WmsDispatchTasks = <ThrowOnError extends boolean = false>(options: Options<PostApiV1WmsDispatchTasksData, ThrowOnError>) => (options.client ?? client).post<PostApiV1WmsDispatchTasksResponses, unknown, ThrowOnError>({
    url: '/api/v1/wms/dispatch/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 删除/取消指定的 AGV 任务
 */
export const deleteApiV1WmsDispatchTasksByTaskId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiV1WmsDispatchTasksByTaskIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiV1WmsDispatchTasksByTaskIdResponses, unknown, ThrowOnError>({ url: '/api/v1/wms/dispatch/tasks/{taskId}', ...options });

export const getApiWmsLocationsTestException = <ThrowOnError extends boolean = false>(options?: Options<GetApiWmsLocationsTestExceptionData, ThrowOnError>) => (options?.client ?? client).get<GetApiWmsLocationsTestExceptionResponses, unknown, ThrowOnError>({ url: '/api/wms/locations/test-exception', ...options });

export const postApiWmsLocationsByLocationCodeLock = <ThrowOnError extends boolean = false>(options: Options<PostApiWmsLocationsByLocationCodeLockData, ThrowOnError>) => (options.client ?? client).post<PostApiWmsLocationsByLocationCodeLockResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/wms/locations/{locationCode}/lock',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiWmsLocationsTestDb = <ThrowOnError extends boolean = false>(options?: Options<GetApiWmsLocationsTestDbData, ThrowOnError>) => (options?.client ?? client).get<GetApiWmsLocationsTestDbResponses, unknown, ThrowOnError>({ url: '/api/wms/locations/test-db', ...options });

export const getApiWmsLocationsTestTelemetry = <ThrowOnError extends boolean = false>(options?: Options<GetApiWmsLocationsTestTelemetryData, ThrowOnError>) => (options?.client ?? client).get<GetApiWmsLocationsTestTelemetryResponses, unknown, ThrowOnError>({ url: '/api/wms/locations/test-telemetry', ...options });

export const postApiSysAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiSysAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostApiSysAuthLoginResponses, unknown, ThrowOnError>({
    url: '/api/sys/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 10. 接收上报车辆状态
 * 请求地址: http://{{server}}:9000/api/v1/xinsong/report_robot_status
 */
export const postApiV1XinsongReportRobotStatus = <ThrowOnError extends boolean = false>(options: Options<PostApiV1XinsongReportRobotStatusData, ThrowOnError>) => (options.client ?? client).post<PostApiV1XinsongReportRobotStatusResponses, unknown, ThrowOnError>({
    url: '/api/v1/xinsong/report_robot_status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
