// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:5188/' | (string & {});
};

export type ApiResponse = {
    code?: number | string;
    message?: string;
    isSuccess?: boolean;
};

export type DispatchAgvCommand = {
    locationCode: string;
    taskId: string;
    taskType: string;
};

export type LockLocationRequest = {
    taskId?: string;
};

export type LoginCommand = {
    username: string;
    password: string;
};

export type XinSongBatteryInfo = {
    soc?: string;
};

export type XinSongRobotStatusRequest = {
    AGV_serial?: string;
    status?: number | string;
    x_position?: string;
    y_position?: string;
    theta?: string;
    battery_info?: null | XinSongBatteryInfo;
};

export type PostApiV1WmsDispatchTasksData = {
    body: DispatchAgvCommand;
    path?: never;
    query?: never;
    url: '/api/v1/wms/dispatch/tasks';
};

export type PostApiV1WmsDispatchTasksResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1WmsDispatchTasksByTaskIdData = {
    body?: never;
    path: {
        taskId: string;
    };
    query?: never;
    url: '/api/v1/wms/dispatch/tasks/{taskId}';
};

export type DeleteApiV1WmsDispatchTasksByTaskIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiWmsLocationsTestExceptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wms/locations/test-exception';
};

export type GetApiWmsLocationsTestExceptionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiWmsLocationsByLocationCodeLockData = {
    body: LockLocationRequest;
    path: {
        locationCode: string;
    };
    query?: never;
    url: '/api/wms/locations/{locationCode}/lock';
};

export type PostApiWmsLocationsByLocationCodeLockResponses = {
    /**
     * OK
     */
    200: ApiResponse;
};

export type PostApiWmsLocationsByLocationCodeLockResponse = PostApiWmsLocationsByLocationCodeLockResponses[keyof PostApiWmsLocationsByLocationCodeLockResponses];

export type GetApiWmsLocationsTestDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wms/locations/test-db';
};

export type GetApiWmsLocationsTestDbResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiWmsLocationsTestTelemetryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/wms/locations/test-telemetry';
};

export type GetApiWmsLocationsTestTelemetryResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiSysAuthLoginData = {
    body: LoginCommand;
    path?: never;
    query?: never;
    url: '/api/sys/auth/login';
};

export type PostApiSysAuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1XinsongReportRobotStatusData = {
    body: XinSongRobotStatusRequest;
    path?: never;
    query?: never;
    url: '/api/v1/xinsong/report_robot_status';
};

export type PostApiV1XinsongReportRobotStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};
